In [134]:
import pandas as pd
import numpy as np
import re
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.model_selection import train_test_split
import json

from keras.preprocessing.sequence import pad_sequences
from keras.optimizers import Adam
from keras.models import Sequential, Model
from keras.layers import Input, Dense, Reshape, Flatten, Dropout, LSTM, Embedding, SpatialDropout1D
from keras.layers.advanced_activations import LeakyReLU
from keras.layers import BatchNormalization, Activation, ZeroPadding2D

In [135]:
df_idf = pd.read_csv('amazon/reviews.csv')
df_dataset = pd.read_json('clothing_dataset/renttherunway_final_data.json', lines = True)

In [136]:
def pre_process(text):
    # to lowercase
    text=text.lower()
    
    # remove tags
    text = re.sub("&lt;/?.*?&gt;", "&lt;&gt; ", text)
    
    # remove special characters and digits
    text = re.sub("(\\d|\\W)+", " ", text)
    
    return text

def get_stop_words(stop_file_path):
    with open(stop_file_path, 'r', encoding='utf-8') as f:
        stopwords = f.readlines()
        stop_set = set(m.strip() for m in stopwords)
        return frozenset(stop_set)

In [137]:
df_idf['text'] = df_idf['title'] + " " + df_idf['body']
df_idf['text'] = df_idf['text'].apply(lambda x: pre_process(str(x)))

df_dataset['text'] = df_dataset['review_summary'] + " " + df_dataset['review_text']
df_dataset['text'] = df_dataset['text'].apply(lambda x: pre_process(str(x)))

sub_dataset = df_dataset[['text', 'rating']]

In [138]:
all_data = df_idf['text'].append(sub_dataset['text'])
all_rating = df_idf['rating'].append(sub_dataset['rating'])

In [139]:
y = all_rating
y[:len(df_idf)] = y[:len(df_idf)].apply(lambda x: 1 if x > 3.5 else 0)#y.apply(lambda x: 1 if x > 3.5 else 0) 
y[len(df_idf):] = y[len(df_idf):].apply(lambda x: 1 if x > 5 else 0)#y.apply(lambda x: 1 if x > 3.5 else 0) 
y = y.to_numpy()

In [140]:
# Change this to use both datasets
#X_train, X_test, y_train, y_test = train_test_split(all_data, y, test_size=0.1, random_state=37)
# X_train = df_dataset['text']
# y_train = y[len(df_idf):]

# X_test = df_idf['text'].to_numpy()
# y_test = y[:len(df_idf)]

# print('# Train data samples:', X_train.shape)
# print('# Test data samples:', X_test.shape)

# print('Sample train', X_train[0])
# print('\nSample test', X_test[0])
# print(X_train.shape, y_train.shape)
# print(X_test.shape, y_test.shape)
# assert X_train.shape[0] == y_train.shape[0]
# assert X_test.shape[0] == y_test.shape[0]

In [141]:
MAX_LEN = 5260
GLOVE_DIM = 300
NB_WORDS = 49781

In [142]:
from keras.preprocessing.text import Tokenizer

tk = Tokenizer(num_words=NB_WORDS,
               filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
               split=" ")
tk.fit_on_texts(all_data)

all_data_seq = tk.texts_to_sequences(all_data)

In [143]:
X_train_seq = all_data_seq[len(df_idf):]
X_test_seq = all_data_seq[:len(df_idf)]

y_train = y[len(df_idf):]
y_test = y[:len(df_idf)]

In [144]:
seq_lengths = all_data.apply(lambda x: len(x.split(' ')))
print(seq_lengths.describe())

count    275359.000000
mean         63.517557
std          69.966379
min           1.000000
25%          26.000000
50%          50.000000
75%          82.000000
max        5260.000000
Name: text, dtype: float64


In [145]:
X_train_seq_trunc = pad_sequences(X_train_seq, maxlen=MAX_LEN)
X_test_seq_trunc = pad_sequences(X_test_seq, maxlen=MAX_LEN)

In [186]:
# # This is to split the X_test_seq_trunc in two normalize dataset for GANs
# print(X_test_seq_trunc.shape)

# positives = X_test_seq_trunc[0:1]
# negatives = X_test_seq_trunc[0:1]

# normalized_data = X_test_seq_trunc[0:1]

# print(positives.shape)

# for i in range(0, y_test.shape[0]):
#     if y_test[i] == 1:
#         positives = np.append(positives, X_test_seq_trunc[i:(i+1)], axis=0)
#     else:
#         negatives = np.append(negatives, X_test_seq_trunc[i:(i+1)], axis=0)
        
# iter_ = min(positives.shape[0], negatives.shape[0])
# for i in range(0, iter_):
#     normalized_data = np.append(normalized_data, positives[i:(i+1)], axis=0)
#     normalized_data = np.append(normalized_data, negatives[i:(i+1)], axis=0)
    
        
# print(positives.shape, negatives.shape, normalized_data.shape)

# for i in range(0, 5000):
#     if(positives[0:1, i] != 0):
#         print(positives[0:1, i], X_test_seq_trunc[0:1, i], i)

half_batch = int(128/2)

idx = np.random.randint(0, X_test_seq_trunc.shape[1], half_batch)
samp = np.array([])
count = 0
for i in range(0, half_batch):
    if count != half_batch/2:
        idx = np.random.randint(0, X_test_seq_trunc.shape[1], 1)
        while(y_test[idx] == 0):
            idx = np.random.randint(0, X_test_seq_trunc.shape[1], 1)
        samp = np.append(samp, idx, axis=0)
        
        while(y_test[idx] == 1):
            idx = np.random.randint(0, X_test_seq_trunc.shape[1], 1)
        samp = np.append(samp, idx, axis=0)
        count += 1
        


# # samp = X_test_seq_trunc[idx]
samp = samp.astype(int)

print(X_test_seq_trunc[samp])
print(y_test[samp])
print(samp)
df_idf['text'][samp]

[[    0     0     0 ...    84   204   520]
 [    0     0     0 ...     1   792 23123]
 [    0     0     0 ...  1027    16     5]
 ...
 [    0     0     0 ...     6    26   525]
 [    0     0     0 ...   177     1   982]
 [    0     0     0 ...    43    20   708]]
[1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.
 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.
 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
[1316 2351 3203 3428  438 4732 1238 3755 4516 3807 1202 2107 2453  211
 5116  491 2304 4664 2475  203 2261 1930  933 2988 1155  286  881  818
 2526 3964 4557 1685  874 3797 4419  323  410 2009 4719 3970 3222 1220
 2900 5233 3726 2635 1843 5048 1681 5110 1290  925 5257 1959 1338 3823
 2905 3582 2938  349  209 3179 2263 3545]


1316    perfect for all my daily activities i loved th...
2351    not a good emergency only phone i activated th...
3203    flawless coming from another smartphone that w...
3428    i actually never imagined a phone could be thi...
438     excellent service responses excellent service ...
4732    absolutely hate it this phone could not be wor...
1238    so far so good have only had it for days but s...
3755    it happens every day now and it s annoying bec...
4516    five stars i already wrote a review they are g...
3807    think twice before buying there are definitely...
1202    had exactly what i needed when i needed it tha...
2107    no external memory can t save items this was m...
2453    i like this phone and i give it four stars out...
211     it s ok except for the browser button seems li...
5116    excellent bought the phone for my daughter rec...
491     make sure your aware that it can only be used ...
2304              i love it just what i needed i love it 
4664    one st

In [147]:
print(X_train_seq_trunc[10])  # Example of padded sequence
print(X_train_seq_trunc.shape)
print(X_test_seq_trunc.shape)
print(y_train.shape)
print(y_test.shape)

[  0   0   0 ...  61  14 316]
(192544, 5260)
(82815, 5260)
(192544,)
(82815,)


In [148]:
X_train_emb, X_valid_emb, y_train_emb, y_valid_emb = train_test_split(X_train_seq_trunc, y_train, test_size=0.1, random_state=37)

assert X_valid_emb.shape[0] == y_valid_emb.shape[0]
assert X_train_emb.shape[0] == y_train_emb.shape[0]

print('Shape of validation set:', X_valid_emb.shape)

Shape of validation set: (19255, 5260)


In [149]:
# This read the embeddings
# glove_file = 'glove.42B.' + str(GLOVE_DIM) + 'd.txt'
# emb_dict = {}
# glove = open(glove_file)
# for line in glove:
#     values = line.split()
#     word = values[0]
#     vector = np.asarray(values[1:], dtype='float32')
#     emb_dict[word] = vector
# glove.close()

In [150]:
airline_words = ['car', 'nice', 'flight', 'luggage']
for w in airline_words:
    if w in emb_dict.keys():
        print('Found the word {} in the dictionary'.format(w))
# print(emb_dict)

Found the word car in the dictionary
Found the word nice in the dictionary
Found the word flight in the dictionary
Found the word luggage in the dictionary


In [151]:
# Here we build a matrix that represent words and it corresponding emdg
emb_matrix = np.zeros((NB_WORDS, GLOVE_DIM))

for w, i in tk.word_index.items():
    if i < NB_WORDS:
        vect = emb_dict.get(w)
        if vect is not None:
            emb_matrix[i] = vect
    else:
        break

In [152]:
glove_model = Sequential()
glove_model.add(Embedding(NB_WORDS, GLOVE_DIM, input_length=MAX_LEN))
# glove_model.add(LSTM(GLOVE_DIM, return_sequences=True))
# glove_model.add(LSTM(GLOVE_DIM, return_sequences=True))
glove_model.add(Flatten())
glove_model.add(Dense(1, activation='sigmoid'))
glove_model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 5260, 300)         14934300  
_________________________________________________________________
flatten_1 (Flatten)          (None, 1578000)           0         
_________________________________________________________________
dense_15 (Dense)             (None, 1)                 1578001   
Total params: 16,512,301
Trainable params: 16,512,301
Non-trainable params: 0
_________________________________________________________________


In [153]:
glove_model.layers[0].set_weights([emb_matrix])
glove_model.layers[0].trainable = False

glove_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [154]:
history = glove_model.fit(X_train_emb
                       , y_train_emb
                       , epochs=5
                       , batch_size=32
                       , validation_data=(X_valid_emb, y_valid_emb)
                       , verbose=1)

Train on 173289 samples, validate on 19255 samples
Epoch 1/5
173289/173289 [==============================] - 637s 4ms/step - loss: 0.1121 - acc: 0.9751 - val_loss: 0.1034 - val_acc: 0.9747
Epoch 2/5
173289/173289 [==============================] - 680s 4ms/step - loss: 0.0806 - acc: 0.9791 - val_loss: 0.1231 - val_acc: 0.9727
Epoch 3/5
173289/173289 [==============================] - 628s 4ms/step - loss: 0.0675 - acc: 0.9819 - val_loss: 0.1317 - val_acc: 0.9774
Epoch 4/5
173289/173289 [==============================] - 658s 4ms/step - loss: 0.0589 - acc: 0.9838 - val_loss: 0.1307 - val_acc: 0.9760
Epoch 5/5
173289/173289 [==============================] - 585s 3ms/step - loss: 0.0524 - acc: 0.9851 - val_loss: 0.1415 - val_acc: 0.9708


In [155]:
print(glove_model.predict(X_train_emb[0:1]))
print(X_train_emb[0].shape)

[[0.9999999]]
(5260,)


# Adversarial Neural Network

In this section we start building the GANs, this model takes the word embedding and generate new embeddings that are similar to the given ones. 

In [156]:
def build_generator(shape):
    img_shape = shape
    noise_shape = (100,)

    model = Sequential()

    model.add(Dense(256, input_shape=noise_shape))
    model.add(LeakyReLU(alpha=0.2))
    model.add(BatchNormalization(momentum=0.8))
    model.add(Dense(512))
    model.add(LeakyReLU(alpha=0.2))
    model.add(BatchNormalization(momentum=0.8))
    model.add(Dense(1024))
    model.add(LeakyReLU(alpha=0.2))
    model.add(BatchNormalization(momentum=0.8))
    model.add(Dense(np.prod(img_shape), activation='tanh'))
    model.add(Reshape(img_shape))

    model.summary()

    noise = Input(shape=noise_shape)
    img = model(noise)

    return Model(noise, img)

def build_discriminator(shape):

    img_shape = shape

    model = Sequential()

#     model.add(Flatten(input_shape=img_shape)) # is one dimension
    model.add(Dense(512, input_shape=img_shape))
    model.add(LeakyReLU(alpha=0.2))
    model.add(Dense(256))
    model.add(LeakyReLU(alpha=0.2))
    model.add(Dense(1, activation='sigmoid'))
    model.summary()

    img = Input(shape=img_shape)
    validity = model(img)

    return Model(img, validity)


In [157]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
def results(pred, actual):
    results = confusion_matrix(actual, pred)
    print('Confusion Matrix :')
    print(results)
    print ('Accuracy Score :',accuracy_score(actual, pred))
    print ('Report : ')
    print(classification_report(actual, pred))
    print()

In [158]:
img_rows = 1
img_cols = X_train_emb[0].shape
img_shape = (img_cols)

optimizer = Adam(0.0002, 0.5)

# Build and compile the discriminator
discriminator = build_discriminator(img_shape)
discriminator.compile(loss='binary_crossentropy',
    optimizer=optimizer,
    metrics=['accuracy'])

# Build and compile the generator
generator = build_generator(img_shape)
generator.compile(loss='binary_crossentropy', optimizer=optimizer)

# The generator takes noise as input and generated imgs
z = Input(shape=(100,))
img = generator(z)

# For the combined model we will only train the generator
discriminator.trainable = False

# The valid takes generated images as input and determines validity
valid = discriminator(img)

# The combined model  (stacked generator and discriminator) takes
# noise as input => generates images => determines validity
combined = Model(z, valid)
combined.compile(loss='binary_crossentropy', optimizer=optimizer)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_16 (Dense)             (None, 512)               2693632   
_________________________________________________________________
leaky_re_lu_11 (LeakyReLU)   (None, 512)               0         
_________________________________________________________________
dense_17 (Dense)             (None, 256)               131328    
_________________________________________________________________
leaky_re_lu_12 (LeakyReLU)   (None, 256)               0         
_________________________________________________________________
dense_18 (Dense)             (None, 1)                 257       
Total params: 2,825,217
Trainable params: 2,825,217
Non-trainable params: 0
_________________________________________________________________
_________________________________________________________________
Layer (type)                 Output Shape              Param #   


In [159]:
def train(epochs, data, batch_size=128):


        # Rescale -1 to 1
        X_train = data #(X_train.astype(np.float32) - 127.5) / 127.5
#         X_train = np.expand_dims(X_train, axis=3)

        half_batch = int(batch_size / 2)

        for epoch in range(epochs):

            # ---------------------
            #  Train Discriminator
            # ---------------------

            # Select a random half batch of images
#             idx = np.random.randint(0, X_train.shape[1], half_batch)
#             imgs = X_train[idx]

            idx = np.random.randint(0, X_train.shape[1], half_batch)
            samp = np.array([])
            count = 0
            for i in range(0, half_batch):
                if count != half_batch/2:
                    idx = np.random.randint(0, X_train.shape[1], 1)
                    while(y_test[idx] == 0):
                        idx = np.random.randint(0, X_train.shape[1], 1)
                    samp = np.append(samp, idx, axis=0)

                    while(y_test[idx] == 1):
                        idx = np.random.randint(0, X_train.shape[1], 1)
                    samp = np.append(samp, idx, axis=0)
                    count += 1


            # samp = X_test_seq_trunc[idx]
            samp = samp.astype(int)
            imgs = X_train[samp]
#             print(np.sum(y_test[samp]))
            
            noise = np.random.normal(0, 1, (half_batch, 100))

            # Generate a half batch of new images
            gen_imgs = np.round(generator.predict(noise))

            # Train the discriminator
            d_loss_real = discriminator.train_on_batch(imgs, np.ones((half_batch, 1)))
            d_loss_fake = discriminator.train_on_batch(gen_imgs, np.zeros((half_batch, 1)))
            d_loss = 0.5 * np.add(d_loss_real, d_loss_fake)


            # ---------------------
            #  Train Generator
            # ---------------------

            noise = np.random.normal(0, 1, (batch_size, 100))

            # The generator wants the discriminator to label the generated samples
            # as valid (ones)
            valid_y = np.array([1] * batch_size)

            # Train the generator
            g_loss = combined.train_on_batch(noise, valid_y)

            # Plot the progress
            print ("%d [D loss: %f, acc.: %.2f%%] [G loss: %f]" % (epoch, d_loss[0], 100*d_loss[1], g_loss))



In [160]:
train(epochs=4000, data=X_test_seq_trunc) # Generate data similar to the second dataset

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/keras/engine/training.py:490: UserWarning: Discrepancy between trainable weights and collected trainable weights, did you set `model.trainable` without calling `model.compile` after ?
  'Discrepancy between trainable weights and collected trainable'


0 [D loss: 1.810067, acc.: 36.72%] [G loss: 0.641288]
1 [D loss: 0.822508, acc.: 55.47%] [G loss: 0.539981]
2 [D loss: 0.704065, acc.: 53.91%] [G loss: 0.440695]
3 [D loss: 0.705125, acc.: 54.69%] [G loss: 0.373934]
4 [D loss: 0.812922, acc.: 51.56%] [G loss: 0.345146]
5 [D loss: 1.087976, acc.: 50.00%] [G loss: 0.308388]
6 [D loss: 0.958924, acc.: 50.78%] [G loss: 0.310668]
7 [D loss: 1.603963, acc.: 47.66%] [G loss: 0.300471]
8 [D loss: 1.038210, acc.: 49.22%] [G loss: 0.290471]
9 [D loss: 1.533416, acc.: 46.88%] [G loss: 0.290719]
10 [D loss: 1.701197, acc.: 46.88%] [G loss: 0.221435]
11 [D loss: 1.214371, acc.: 50.78%] [G loss: 0.238506]
12 [D loss: 1.186348, acc.: 50.78%] [G loss: 0.224354]
13 [D loss: 1.349773, acc.: 49.22%] [G loss: 0.267747]
14 [D loss: 0.933843, acc.: 50.78%] [G loss: 0.281795]
15 [D loss: 0.869056, acc.: 56.25%] [G loss: 0.306148]
16 [D loss: 1.054489, acc.: 53.12%] [G loss: 0.311180]
17 [D loss: 1.115238, acc.: 53.91%] [G loss: 0.314307]
18 [D loss: 0.981008

149 [D loss: 1.709611, acc.: 70.31%] [G loss: 0.947220]
150 [D loss: 0.672634, acc.: 71.09%] [G loss: 0.922792]
151 [D loss: 1.439794, acc.: 69.53%] [G loss: 0.871985]
152 [D loss: 1.623712, acc.: 56.25%] [G loss: 0.951732]
153 [D loss: 1.828401, acc.: 64.84%] [G loss: 0.968485]
154 [D loss: 2.022963, acc.: 64.84%] [G loss: 0.956028]
155 [D loss: 1.515982, acc.: 64.84%] [G loss: 0.916122]
156 [D loss: 1.453091, acc.: 71.88%] [G loss: 0.906584]
157 [D loss: 2.502814, acc.: 57.81%] [G loss: 0.657890]
158 [D loss: 1.270637, acc.: 59.38%] [G loss: 0.802096]
159 [D loss: 1.695183, acc.: 62.50%] [G loss: 0.919700]
160 [D loss: 1.172889, acc.: 67.19%] [G loss: 0.973992]
161 [D loss: 1.459300, acc.: 70.31%] [G loss: 0.979617]
162 [D loss: 1.608061, acc.: 64.06%] [G loss: 1.025523]
163 [D loss: 1.777737, acc.: 64.84%] [G loss: 0.963184]
164 [D loss: 1.943427, acc.: 65.62%] [G loss: 0.967020]
165 [D loss: 1.523937, acc.: 59.38%] [G loss: 0.947238]
166 [D loss: 1.295017, acc.: 63.28%] [G loss: 0.

296 [D loss: 0.714596, acc.: 89.06%] [G loss: 1.195927]
297 [D loss: 1.293511, acc.: 78.12%] [G loss: 1.234422]
298 [D loss: 1.510658, acc.: 80.47%] [G loss: 1.265035]
299 [D loss: 0.834029, acc.: 79.69%] [G loss: 1.246167]
300 [D loss: 0.905931, acc.: 82.81%] [G loss: 1.321465]
301 [D loss: 0.521523, acc.: 86.72%] [G loss: 1.316330]
302 [D loss: 1.369074, acc.: 81.25%] [G loss: 1.340075]
303 [D loss: 1.119299, acc.: 83.59%] [G loss: 1.299991]
304 [D loss: 1.496243, acc.: 82.81%] [G loss: 1.254269]
305 [D loss: 1.473108, acc.: 85.16%] [G loss: 1.294131]
306 [D loss: 1.363028, acc.: 85.16%] [G loss: 1.247320]
307 [D loss: 1.118316, acc.: 85.94%] [G loss: 1.321675]
308 [D loss: 1.407594, acc.: 75.00%] [G loss: 1.346804]
309 [D loss: 2.245696, acc.: 75.00%] [G loss: 1.397185]
310 [D loss: 0.618976, acc.: 86.72%] [G loss: 1.304172]
311 [D loss: 2.029838, acc.: 75.78%] [G loss: 1.323601]
312 [D loss: 1.461155, acc.: 86.72%] [G loss: 1.371235]
313 [D loss: 1.732625, acc.: 82.03%] [G loss: 1.

443 [D loss: 2.003702, acc.: 76.56%] [G loss: 1.568848]
444 [D loss: 1.629616, acc.: 76.56%] [G loss: 1.642401]
445 [D loss: 1.702112, acc.: 50.00%] [G loss: 0.364613]
446 [D loss: 1.462091, acc.: 50.78%] [G loss: 0.903962]
447 [D loss: 0.520578, acc.: 74.22%] [G loss: 1.923959]
448 [D loss: 0.290172, acc.: 90.62%] [G loss: 2.300140]
449 [D loss: 0.383202, acc.: 88.28%] [G loss: 1.984142]
450 [D loss: 0.265164, acc.: 89.06%] [G loss: 1.728876]
451 [D loss: 0.400966, acc.: 86.72%] [G loss: 1.469148]
452 [D loss: 0.474052, acc.: 82.81%] [G loss: 1.483725]
453 [D loss: 0.502260, acc.: 77.34%] [G loss: 1.540681]
454 [D loss: 0.325179, acc.: 85.94%] [G loss: 1.571933]
455 [D loss: 0.512734, acc.: 77.34%] [G loss: 1.402898]
456 [D loss: 0.580449, acc.: 75.00%] [G loss: 1.454484]
457 [D loss: 0.689765, acc.: 82.81%] [G loss: 1.508670]
458 [D loss: 1.205544, acc.: 80.47%] [G loss: 1.456156]
459 [D loss: 0.707895, acc.: 79.69%] [G loss: 1.387047]
460 [D loss: 0.694075, acc.: 78.12%] [G loss: 1.

590 [D loss: 1.363073, acc.: 83.59%] [G loss: 2.512846]
591 [D loss: 1.633005, acc.: 82.03%] [G loss: 4.290456]
592 [D loss: 1.405654, acc.: 76.56%] [G loss: 3.692740]
593 [D loss: 1.304805, acc.: 78.91%] [G loss: 3.398654]
594 [D loss: 0.629678, acc.: 82.81%] [G loss: 3.718849]
595 [D loss: 1.413895, acc.: 85.16%] [G loss: 3.452236]
596 [D loss: 0.989781, acc.: 82.03%] [G loss: 3.335234]
597 [D loss: 1.358843, acc.: 82.81%] [G loss: 3.503377]
598 [D loss: 1.442609, acc.: 74.22%] [G loss: 3.383338]
599 [D loss: 1.737278, acc.: 72.66%] [G loss: 3.826262]
600 [D loss: 0.908668, acc.: 86.72%] [G loss: 3.643501]
601 [D loss: 0.749052, acc.: 91.41%] [G loss: 2.876334]
602 [D loss: 0.782199, acc.: 91.41%] [G loss: 2.437479]
603 [D loss: 1.762811, acc.: 71.09%] [G loss: 3.670056]
604 [D loss: 1.488532, acc.: 71.88%] [G loss: 3.267539]
605 [D loss: 1.051528, acc.: 78.12%] [G loss: 2.906778]
606 [D loss: 0.493251, acc.: 82.03%] [G loss: 3.014779]
607 [D loss: 0.485221, acc.: 80.47%] [G loss: 3.

737 [D loss: 0.580509, acc.: 94.53%] [G loss: 2.531780]
738 [D loss: 0.824377, acc.: 95.31%] [G loss: 2.230260]
739 [D loss: 0.566771, acc.: 96.09%] [G loss: 2.214003]
740 [D loss: 1.341032, acc.: 91.41%] [G loss: 2.352428]
741 [D loss: 0.707575, acc.: 93.75%] [G loss: 2.536540]
742 [D loss: 0.571456, acc.: 96.09%] [G loss: 2.715281]
743 [D loss: 1.316275, acc.: 92.19%] [G loss: 2.460939]
744 [D loss: 0.314392, acc.: 97.66%] [G loss: 2.358516]
745 [D loss: 0.960277, acc.: 93.75%] [G loss: 1.973122]
746 [D loss: 0.969865, acc.: 92.97%] [G loss: 2.231240]
747 [D loss: 0.732484, acc.: 95.31%] [G loss: 2.521386]
748 [D loss: 0.980284, acc.: 92.19%] [G loss: 2.956102]
749 [D loss: 1.039448, acc.: 87.50%] [G loss: 3.466633]
750 [D loss: 0.863772, acc.: 92.19%] [G loss: 3.260241]
751 [D loss: 0.695952, acc.: 95.31%] [G loss: 2.957492]
752 [D loss: 0.406425, acc.: 96.88%] [G loss: 2.645305]
753 [D loss: 1.049145, acc.: 93.75%] [G loss: 2.373531]
754 [D loss: 0.685589, acc.: 96.09%] [G loss: 2.

884 [D loss: 0.052818, acc.: 98.44%] [G loss: 4.491965]
885 [D loss: 0.428790, acc.: 96.09%] [G loss: 3.820748]
886 [D loss: 0.811947, acc.: 94.53%] [G loss: 3.299686]
887 [D loss: 0.699215, acc.: 94.53%] [G loss: 3.265159]
888 [D loss: 1.220610, acc.: 88.28%] [G loss: 2.915794]
889 [D loss: 0.462040, acc.: 95.31%] [G loss: 2.942919]
890 [D loss: 0.441209, acc.: 96.09%] [G loss: 2.783367]
891 [D loss: 0.854607, acc.: 92.19%] [G loss: 2.403064]
892 [D loss: 0.194256, acc.: 97.66%] [G loss: 2.081568]
893 [D loss: 0.765372, acc.: 91.41%] [G loss: 1.921470]
894 [D loss: 0.227647, acc.: 98.44%] [G loss: 1.941106]
895 [D loss: 0.575588, acc.: 96.88%] [G loss: 1.910451]
896 [D loss: 0.475513, acc.: 96.09%] [G loss: 1.877444]
897 [D loss: 1.017362, acc.: 89.84%] [G loss: 1.939756]
898 [D loss: 0.737863, acc.: 91.41%] [G loss: 2.213669]
899 [D loss: 0.286982, acc.: 92.97%] [G loss: 2.828068]
900 [D loss: 0.782244, acc.: 78.91%] [G loss: 3.857322]
901 [D loss: 0.809404, acc.: 78.12%] [G loss: 4.

1030 [D loss: 0.254147, acc.: 94.53%] [G loss: 2.034827]
1031 [D loss: 0.242433, acc.: 94.53%] [G loss: 1.947265]
1032 [D loss: 0.217875, acc.: 97.66%] [G loss: 1.959361]
1033 [D loss: 0.358638, acc.: 95.31%] [G loss: 1.975897]
1034 [D loss: 0.211355, acc.: 98.44%] [G loss: 2.007083]
1035 [D loss: 0.187584, acc.: 98.44%] [G loss: 2.108546]
1036 [D loss: 0.832736, acc.: 94.53%] [G loss: 2.410025]
1037 [D loss: 0.461738, acc.: 95.31%] [G loss: 2.254279]
1038 [D loss: 0.351242, acc.: 95.31%] [G loss: 1.786477]
1039 [D loss: 0.498617, acc.: 94.53%] [G loss: 1.994265]
1040 [D loss: 0.587747, acc.: 95.31%] [G loss: 2.063732]
1041 [D loss: 0.701250, acc.: 95.31%] [G loss: 2.162156]
1042 [D loss: 0.312589, acc.: 98.44%] [G loss: 2.188044]
1043 [D loss: 0.318148, acc.: 96.88%] [G loss: 2.330760]
1044 [D loss: 0.569779, acc.: 95.31%] [G loss: 2.177872]
1045 [D loss: 0.435308, acc.: 96.88%] [G loss: 2.312885]
1046 [D loss: 0.293216, acc.: 98.44%] [G loss: 2.743413]
1047 [D loss: 0.429672, acc.: 9

1174 [D loss: 0.473679, acc.: 94.53%] [G loss: 3.096764]
1175 [D loss: 0.958694, acc.: 92.97%] [G loss: 2.984654]
1176 [D loss: 0.431283, acc.: 96.88%] [G loss: 2.841341]
1177 [D loss: 0.677851, acc.: 96.09%] [G loss: 2.891844]
1178 [D loss: 0.805976, acc.: 94.53%] [G loss: 2.444227]
1179 [D loss: 0.350518, acc.: 96.09%] [G loss: 2.152921]
1180 [D loss: 0.371985, acc.: 95.31%] [G loss: 2.283623]
1181 [D loss: 0.739270, acc.: 88.28%] [G loss: 1.948515]
1182 [D loss: 0.216793, acc.: 97.66%] [G loss: 2.184646]
1183 [D loss: 0.395160, acc.: 89.84%] [G loss: 3.401247]
1184 [D loss: 0.801651, acc.: 72.66%] [G loss: 5.791682]
1185 [D loss: 1.832942, acc.: 75.78%] [G loss: 6.965136]
1186 [D loss: 0.174204, acc.: 97.66%] [G loss: 6.538568]
1187 [D loss: 0.937651, acc.: 75.00%] [G loss: 8.297983]
1188 [D loss: 0.527958, acc.: 96.09%] [G loss: 7.490407]
1189 [D loss: 0.215517, acc.: 92.19%] [G loss: 6.766553]
1190 [D loss: 0.182548, acc.: 96.09%] [G loss: 5.754239]
1191 [D loss: 0.037550, acc.: 9

1318 [D loss: 0.764829, acc.: 79.69%] [G loss: 5.474631]
1319 [D loss: 0.497609, acc.: 87.50%] [G loss: 6.774199]
1320 [D loss: 0.462509, acc.: 89.06%] [G loss: 6.479511]
1321 [D loss: 0.670147, acc.: 81.25%] [G loss: 7.255795]
1322 [D loss: 0.137896, acc.: 93.75%] [G loss: 6.243711]
1323 [D loss: 0.196018, acc.: 90.62%] [G loss: 5.177354]
1324 [D loss: 0.374935, acc.: 85.94%] [G loss: 5.023730]
1325 [D loss: 0.317542, acc.: 88.28%] [G loss: 3.430892]
1326 [D loss: 0.569343, acc.: 74.22%] [G loss: 3.606367]
1327 [D loss: 0.250782, acc.: 86.72%] [G loss: 3.259403]
1328 [D loss: 0.520046, acc.: 79.69%] [G loss: 2.453569]
1329 [D loss: 0.637913, acc.: 75.00%] [G loss: 2.968656]
1330 [D loss: 0.665173, acc.: 77.34%] [G loss: 3.899344]
1331 [D loss: 1.928137, acc.: 68.75%] [G loss: 6.196882]
1332 [D loss: 1.077820, acc.: 78.12%] [G loss: 5.264178]
1333 [D loss: 1.057948, acc.: 77.34%] [G loss: 4.473008]
1334 [D loss: 0.468723, acc.: 85.16%] [G loss: 4.270262]
1335 [D loss: 0.355634, acc.: 8

1462 [D loss: 0.668002, acc.: 96.09%] [G loss: 3.559418]
1463 [D loss: 0.209434, acc.: 97.66%] [G loss: 3.475663]
1464 [D loss: 0.903741, acc.: 94.53%] [G loss: 3.240633]
1465 [D loss: 1.052248, acc.: 93.75%] [G loss: 3.247927]
1466 [D loss: 1.026290, acc.: 88.28%] [G loss: 4.381474]
1467 [D loss: 1.086137, acc.: 75.00%] [G loss: 6.722574]
1468 [D loss: 2.885594, acc.: 68.75%] [G loss: 7.226782]
1469 [D loss: 1.364807, acc.: 78.12%] [G loss: 11.052818]
1470 [D loss: 0.255135, acc.: 98.44%] [G loss: 10.784753]
1471 [D loss: 0.116416, acc.: 94.53%] [G loss: 8.572069]
1472 [D loss: 0.502787, acc.: 83.59%] [G loss: 7.860626]
1473 [D loss: 0.097306, acc.: 96.09%] [G loss: 7.609276]
1474 [D loss: 0.147566, acc.: 94.53%] [G loss: 4.828560]
1475 [D loss: 0.111488, acc.: 96.09%] [G loss: 3.337327]
1476 [D loss: 0.351879, acc.: 79.69%] [G loss: 3.469019]
1477 [D loss: 0.261222, acc.: 86.72%] [G loss: 4.346372]
1478 [D loss: 0.990073, acc.: 74.22%] [G loss: 4.905230]
1479 [D loss: 0.704215, acc.:

1606 [D loss: 0.309715, acc.: 98.44%] [G loss: 6.310599]
1607 [D loss: 0.397912, acc.: 97.66%] [G loss: 5.857750]
1608 [D loss: 0.839660, acc.: 92.19%] [G loss: 5.778264]
1609 [D loss: 0.639509, acc.: 96.09%] [G loss: 5.504728]
1610 [D loss: 0.522988, acc.: 96.88%] [G loss: 4.936003]
1611 [D loss: 0.308344, acc.: 96.09%] [G loss: 4.669604]
1612 [D loss: 0.404504, acc.: 97.66%] [G loss: 4.849492]
1613 [D loss: 0.783270, acc.: 95.31%] [G loss: 4.215395]
1614 [D loss: 0.551324, acc.: 96.09%] [G loss: 3.876904]
1615 [D loss: 0.538548, acc.: 96.88%] [G loss: 3.640773]
1616 [D loss: 0.413403, acc.: 97.66%] [G loss: 3.068074]
1617 [D loss: 0.553335, acc.: 96.88%] [G loss: 3.156000]
1618 [D loss: 0.470133, acc.: 94.53%] [G loss: 3.547367]
1619 [D loss: 0.652306, acc.: 75.00%] [G loss: 7.268855]
1620 [D loss: 1.238109, acc.: 78.12%] [G loss: 10.498586]
1621 [D loss: 0.378200, acc.: 97.66%] [G loss: 8.855021]
1622 [D loss: 0.256177, acc.: 91.41%] [G loss: 10.145008]
1623 [D loss: 0.756929, acc.:

1750 [D loss: 0.890496, acc.: 94.53%] [G loss: 5.906577]
1751 [D loss: 0.514146, acc.: 96.88%] [G loss: 5.546717]
1752 [D loss: 0.261406, acc.: 98.44%] [G loss: 5.411427]
1753 [D loss: 0.388429, acc.: 97.66%] [G loss: 5.198998]
1754 [D loss: 0.635488, acc.: 96.09%] [G loss: 4.780179]
1755 [D loss: 0.383555, acc.: 97.66%] [G loss: 5.059393]
1756 [D loss: 0.385289, acc.: 97.66%] [G loss: 4.822477]
1757 [D loss: 1.021072, acc.: 93.75%] [G loss: 4.160891]
1758 [D loss: 1.019096, acc.: 93.75%] [G loss: 4.055942]
1759 [D loss: 0.764250, acc.: 95.31%] [G loss: 3.400274]
1760 [D loss: 0.639579, acc.: 96.09%] [G loss: 3.186845]
1761 [D loss: 0.768803, acc.: 95.31%] [G loss: 3.091965]
1762 [D loss: 0.389322, acc.: 97.66%] [G loss: 2.984588]
1763 [D loss: 0.765818, acc.: 95.31%] [G loss: 2.986525]
1764 [D loss: 0.767329, acc.: 95.31%] [G loss: 3.118134]
1765 [D loss: 0.406475, acc.: 97.66%] [G loss: 2.917994]
1766 [D loss: 0.792871, acc.: 95.31%] [G loss: 2.912718]
1767 [D loss: 0.388594, acc.: 9

1894 [D loss: 0.522620, acc.: 96.88%] [G loss: 6.369873]
1895 [D loss: 0.278463, acc.: 97.66%] [G loss: 6.175148]
1896 [D loss: 0.258002, acc.: 98.44%] [G loss: 4.949441]
1897 [D loss: 0.509548, acc.: 96.88%] [G loss: 4.562176]
1898 [D loss: 0.136426, acc.: 99.22%] [G loss: 4.088519]
1899 [D loss: 0.383924, acc.: 97.66%] [G loss: 4.158783]
1900 [D loss: 0.511974, acc.: 96.88%] [G loss: 4.116891]
1901 [D loss: 0.134845, acc.: 99.22%] [G loss: 3.887917]
1902 [D loss: 0.394706, acc.: 97.66%] [G loss: 3.244633]
1903 [D loss: 0.399031, acc.: 97.66%] [G loss: 3.056710]
1904 [D loss: 0.515559, acc.: 94.53%] [G loss: 2.519110]
1905 [D loss: 0.292973, acc.: 92.97%] [G loss: 2.324840]
1906 [D loss: 0.400361, acc.: 89.06%] [G loss: 5.416085]
1907 [D loss: 1.416712, acc.: 71.88%] [G loss: 7.873730]
1908 [D loss: 0.028145, acc.: 100.00%] [G loss: 7.449153]
1909 [D loss: 0.142498, acc.: 89.06%] [G loss: 10.288149]
1910 [D loss: 0.001717, acc.: 100.00%] [G loss: 9.770560]
1911 [D loss: 0.260541, acc.

2038 [D loss: 0.292663, acc.: 98.44%] [G loss: 2.081869]
2039 [D loss: 0.179486, acc.: 99.22%] [G loss: 2.245575]
2040 [D loss: 0.163512, acc.: 99.22%] [G loss: 2.037573]
2041 [D loss: 0.061840, acc.: 99.22%] [G loss: 2.102753]
2042 [D loss: 0.061785, acc.: 96.88%] [G loss: 2.097381]
2043 [D loss: 0.290444, acc.: 88.28%] [G loss: 3.824034]
2044 [D loss: 0.369856, acc.: 85.94%] [G loss: 5.443656]
2045 [D loss: 0.047205, acc.: 98.44%] [G loss: 4.497663]
2046 [D loss: 0.164615, acc.: 98.44%] [G loss: 4.367145]
2047 [D loss: 0.031619, acc.: 100.00%] [G loss: 3.850348]
2048 [D loss: 0.018786, acc.: 100.00%] [G loss: 2.725895]
2049 [D loss: 0.059098, acc.: 97.66%] [G loss: 2.783548]
2050 [D loss: 0.204128, acc.: 97.66%] [G loss: 2.417653]
2051 [D loss: 0.210237, acc.: 97.66%] [G loss: 2.954684]
2052 [D loss: 0.086723, acc.: 98.44%] [G loss: 3.055507]
2053 [D loss: 0.416548, acc.: 93.75%] [G loss: 3.220129]
2054 [D loss: 0.408815, acc.: 89.06%] [G loss: 5.314135]
2055 [D loss: 0.148032, acc.:

2182 [D loss: 0.139978, acc.: 92.97%] [G loss: 3.238732]
2183 [D loss: 0.513211, acc.: 81.25%] [G loss: 4.806061]
2184 [D loss: 0.307657, acc.: 89.06%] [G loss: 3.765181]
2185 [D loss: 0.207466, acc.: 89.84%] [G loss: 3.397083]
2186 [D loss: 0.313447, acc.: 84.38%] [G loss: 3.670939]
2187 [D loss: 0.379938, acc.: 82.03%] [G loss: 5.177839]
2188 [D loss: 0.220471, acc.: 95.31%] [G loss: 4.889335]
2189 [D loss: 0.282616, acc.: 92.97%] [G loss: 3.701027]
2190 [D loss: 0.168290, acc.: 92.97%] [G loss: 2.989665]
2191 [D loss: 0.449032, acc.: 82.81%] [G loss: 2.838303]
2192 [D loss: 0.349453, acc.: 91.41%] [G loss: 3.417519]
2193 [D loss: 0.655344, acc.: 78.12%] [G loss: 4.974713]
2194 [D loss: 0.515540, acc.: 79.69%] [G loss: 4.525442]
2195 [D loss: 0.404396, acc.: 85.16%] [G loss: 5.536898]
2196 [D loss: 0.152902, acc.: 99.22%] [G loss: 5.516679]
2197 [D loss: 0.153287, acc.: 93.75%] [G loss: 3.716424]
2198 [D loss: 0.240175, acc.: 94.53%] [G loss: 3.360718]
2199 [D loss: 0.233657, acc.: 9

2326 [D loss: 0.085859, acc.: 97.66%] [G loss: 2.873280]
2327 [D loss: 0.129845, acc.: 95.31%] [G loss: 3.198842]
2328 [D loss: 0.260834, acc.: 96.09%] [G loss: 3.000956]
2329 [D loss: 0.429963, acc.: 85.16%] [G loss: 4.027160]
2330 [D loss: 0.229587, acc.: 93.75%] [G loss: 4.091300]
2331 [D loss: 0.139505, acc.: 96.88%] [G loss: 3.888268]
2332 [D loss: 0.176778, acc.: 89.06%] [G loss: 4.885088]
2333 [D loss: 0.162764, acc.: 99.22%] [G loss: 5.109210]
2334 [D loss: 0.032975, acc.: 100.00%] [G loss: 3.742404]
2335 [D loss: 0.179695, acc.: 99.22%] [G loss: 3.103617]
2336 [D loss: 0.075717, acc.: 97.66%] [G loss: 2.759624]
2337 [D loss: 0.033497, acc.: 99.22%] [G loss: 2.664577]
2338 [D loss: 0.080133, acc.: 98.44%] [G loss: 2.307415]
2339 [D loss: 0.058655, acc.: 100.00%] [G loss: 2.333807]
2340 [D loss: 0.559558, acc.: 96.88%] [G loss: 2.483044]
2341 [D loss: 0.182432, acc.: 99.22%] [G loss: 2.667624]
2342 [D loss: 0.207261, acc.: 89.84%] [G loss: 3.796847]
2343 [D loss: 1.499900, acc.:

2470 [D loss: 0.588677, acc.: 90.62%] [G loss: 4.539799]
2471 [D loss: 0.293682, acc.: 96.88%] [G loss: 4.023250]
2472 [D loss: 0.268546, acc.: 98.44%] [G loss: 3.954562]
2473 [D loss: 0.132138, acc.: 99.22%] [G loss: 3.685628]
2474 [D loss: 0.133178, acc.: 99.22%] [G loss: 3.536410]
2475 [D loss: 0.132699, acc.: 99.22%] [G loss: 3.419822]
2476 [D loss: 0.009314, acc.: 100.00%] [G loss: 3.545106]
2477 [D loss: 0.259470, acc.: 98.44%] [G loss: 3.507386]
2478 [D loss: 0.259211, acc.: 98.44%] [G loss: 3.350698]
2479 [D loss: 0.516453, acc.: 96.88%] [G loss: 3.276179]
2480 [D loss: 0.259684, acc.: 98.44%] [G loss: 3.192057]
2481 [D loss: 0.397095, acc.: 97.66%] [G loss: 2.939117]
2482 [D loss: 0.141402, acc.: 99.22%] [G loss: 2.610041]
2483 [D loss: 0.143201, acc.: 99.22%] [G loss: 2.641554]
2484 [D loss: 0.014175, acc.: 100.00%] [G loss: 2.688192]
2485 [D loss: 0.264049, acc.: 98.44%] [G loss: 2.767833]
2486 [D loss: 0.265719, acc.: 98.44%] [G loss: 2.830448]
2487 [D loss: 0.009843, acc.:

2614 [D loss: 0.998329, acc.: 83.59%] [G loss: 10.397417]
2615 [D loss: 0.578820, acc.: 86.72%] [G loss: 12.341606]
2616 [D loss: 0.217014, acc.: 96.88%] [G loss: 11.760064]
2617 [D loss: 0.306273, acc.: 96.09%] [G loss: 11.248123]
2618 [D loss: 0.003176, acc.: 100.00%] [G loss: 11.131734]
2619 [D loss: 0.133280, acc.: 99.22%] [G loss: 10.013818]
2620 [D loss: 0.228642, acc.: 96.88%] [G loss: 9.653904]
2621 [D loss: 0.163064, acc.: 92.19%] [G loss: 14.401031]
2622 [D loss: 0.128546, acc.: 99.22%] [G loss: 14.616596]
2623 [D loss: 0.231943, acc.: 96.09%] [G loss: 14.844856]
2624 [D loss: 0.127733, acc.: 99.22%] [G loss: 14.151695]
2625 [D loss: 0.017130, acc.: 99.22%] [G loss: 13.580857]
2626 [D loss: 0.254743, acc.: 98.44%] [G loss: 12.854867]
2627 [D loss: 0.129013, acc.: 99.22%] [G loss: 12.740452]
2628 [D loss: 0.159454, acc.: 97.66%] [G loss: 11.507914]
2629 [D loss: 0.253919, acc.: 98.44%] [G loss: 11.398494]
2630 [D loss: 0.128439, acc.: 99.22%] [G loss: 10.128923]
2631 [D loss: 

2757 [D loss: 0.007112, acc.: 100.00%] [G loss: 2.712823]
2758 [D loss: 0.008591, acc.: 100.00%] [G loss: 2.523475]
2759 [D loss: 0.388102, acc.: 97.66%] [G loss: 2.660149]
2760 [D loss: 0.260652, acc.: 98.44%] [G loss: 2.723229]
2761 [D loss: 0.008640, acc.: 100.00%] [G loss: 2.940111]
2762 [D loss: 0.131776, acc.: 99.22%] [G loss: 3.195711]
2763 [D loss: 0.383632, acc.: 97.66%] [G loss: 2.974149]
2764 [D loss: 0.260735, acc.: 98.44%] [G loss: 2.915303]
2765 [D loss: 0.260598, acc.: 98.44%] [G loss: 2.929737]
2766 [D loss: 0.162626, acc.: 98.44%] [G loss: 3.015715]
2767 [D loss: 0.135353, acc.: 99.22%] [G loss: 2.831820]
2768 [D loss: 0.258577, acc.: 98.44%] [G loss: 2.740697]
2769 [D loss: 0.006695, acc.: 100.00%] [G loss: 2.764287]
2770 [D loss: 0.006038, acc.: 100.00%] [G loss: 2.840412]
2771 [D loss: 0.006842, acc.: 100.00%] [G loss: 2.857973]
2772 [D loss: 0.006765, acc.: 100.00%] [G loss: 2.961760]
2773 [D loss: 0.257594, acc.: 98.44%] [G loss: 3.048774]
2774 [D loss: 0.132530, 

2901 [D loss: 0.382438, acc.: 97.66%] [G loss: 3.020373]
2902 [D loss: 0.509728, acc.: 96.88%] [G loss: 2.965848]
2903 [D loss: 0.130549, acc.: 99.22%] [G loss: 3.169009]
2904 [D loss: 0.004162, acc.: 100.00%] [G loss: 3.233155]
2905 [D loss: 0.004326, acc.: 100.00%] [G loss: 3.190792]
2906 [D loss: 0.255613, acc.: 98.44%] [G loss: 3.035709]
2907 [D loss: 0.381797, acc.: 97.66%] [G loss: 3.468548]
2908 [D loss: 0.255015, acc.: 98.44%] [G loss: 3.734154]
2909 [D loss: 0.128754, acc.: 99.22%] [G loss: 3.619770]
2910 [D loss: 0.255540, acc.: 98.44%] [G loss: 3.551412]
2911 [D loss: 0.382582, acc.: 97.66%] [G loss: 3.197342]
2912 [D loss: 0.385378, acc.: 97.66%] [G loss: 2.817852]
2913 [D loss: 0.133170, acc.: 99.22%] [G loss: 2.887771]
2914 [D loss: 0.635230, acc.: 96.09%] [G loss: 3.172328]
2915 [D loss: 0.380540, acc.: 97.66%] [G loss: 3.699512]
2916 [D loss: 0.380977, acc.: 97.66%] [G loss: 3.492346]
2917 [D loss: 0.507108, acc.: 96.88%] [G loss: 3.295983]
2918 [D loss: 0.384154, acc.:

3045 [D loss: 0.632639, acc.: 96.09%] [G loss: 3.409022]
3046 [D loss: 0.381034, acc.: 97.66%] [G loss: 3.557764]
3047 [D loss: 0.507426, acc.: 96.88%] [G loss: 3.110640]
3048 [D loss: 0.255289, acc.: 98.44%] [G loss: 3.225723]
3049 [D loss: 0.128302, acc.: 99.22%] [G loss: 3.606665]
3050 [D loss: 0.002664, acc.: 100.00%] [G loss: 3.464699]
3051 [D loss: 0.255072, acc.: 98.44%] [G loss: 3.477468]
3052 [D loss: 0.255101, acc.: 98.44%] [G loss: 3.237553]
3053 [D loss: 0.254949, acc.: 98.44%] [G loss: 3.317204]
3054 [D loss: 0.254139, acc.: 98.44%] [G loss: 3.652123]
3055 [D loss: 0.253693, acc.: 98.44%] [G loss: 4.096678]
3056 [D loss: 0.128072, acc.: 99.22%] [G loss: 3.641603]
3057 [D loss: 0.130062, acc.: 99.22%] [G loss: 3.327340]
3058 [D loss: 0.255927, acc.: 98.44%] [G loss: 3.154578]
3059 [D loss: 0.254631, acc.: 98.44%] [G loss: 3.187774]
3060 [D loss: 0.380453, acc.: 97.66%] [G loss: 3.362757]
3061 [D loss: 0.002352, acc.: 100.00%] [G loss: 3.361473]
3062 [D loss: 0.254563, acc.:

3188 [D loss: 0.259883, acc.: 98.44%] [G loss: 4.453894]
3189 [D loss: 0.012823, acc.: 100.00%] [G loss: 3.767069]
3190 [D loss: 0.261727, acc.: 98.44%] [G loss: 3.920403]
3191 [D loss: 0.515600, acc.: 96.88%] [G loss: 4.237630]
3192 [D loss: 0.509490, acc.: 96.88%] [G loss: 3.715225]
3193 [D loss: 0.146909, acc.: 99.22%] [G loss: 4.307649]
3194 [D loss: 0.005385, acc.: 100.00%] [G loss: 4.157875]
3195 [D loss: 0.259594, acc.: 98.44%] [G loss: 3.616746]
3196 [D loss: 0.135939, acc.: 99.22%] [G loss: 3.214133]
3197 [D loss: 0.268821, acc.: 98.44%] [G loss: 3.852602]
3198 [D loss: 0.506464, acc.: 96.88%] [G loss: 4.152032]
3199 [D loss: 0.008086, acc.: 100.00%] [G loss: 4.348123]
3200 [D loss: 0.131179, acc.: 99.22%] [G loss: 4.267550]
3201 [D loss: 0.138553, acc.: 99.22%] [G loss: 4.112295]
3202 [D loss: 0.268890, acc.: 98.44%] [G loss: 3.840128]
3203 [D loss: 0.399640, acc.: 97.66%] [G loss: 4.194412]
3204 [D loss: 0.255997, acc.: 98.44%] [G loss: 4.417566]
3205 [D loss: 0.132274, acc.

3331 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3332 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3333 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3334 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3335 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3336 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3337 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3338 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3339 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3340 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3341 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3342 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3343 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3344 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3345 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3346 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3347 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.11809

3470 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3471 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3472 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3473 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3474 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3475 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3476 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3477 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3478 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3479 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3480 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3481 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3482 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3483 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3484 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3485 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3486 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.11809

3609 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3610 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3611 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3612 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3613 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3614 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3615 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3616 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3617 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3618 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3619 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3620 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3621 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3622 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3623 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3624 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3625 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.11809

3748 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3749 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3750 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3751 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3752 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3753 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3754 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3755 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3756 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3757 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3758 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3759 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3760 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3761 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3762 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3763 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3764 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.11809

3887 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3888 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3889 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3890 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3891 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3892 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3893 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3894 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3895 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3896 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3897 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3898 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3899 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3900 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3901 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3902 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.118099]
3903 [D loss: 0.000000, acc.: 100.00%] [G loss: 16.11809

# Model Evaluation

Second model trained on the real data

In [161]:
print(X_test_seq_trunc.shape, y_test.shape)

(82815, 5260) (82815,)


In [162]:
X_train_emb2, X_valid_emb2, y_train_emb2, y_valid_emb2 = train_test_split(X_test_seq_trunc, y_test, test_size=0.1, random_state=37)

assert X_valid_emb2.shape[0] == y_valid_emb2.shape[0]
assert X_train_emb2.shape[0] == y_train_emb2.shape[0]

print('Shape of validation set:',X_valid_emb2.shape)

Shape of validation set: (8282, 5260)


In [163]:
glove_model2 = Sequential()
glove_model2.add(Embedding(NB_WORDS, GLOVE_DIM, input_length=MAX_LEN))
# glove_model2.add(LSTM(GLOVE_DIM, return_sequences=True))
# glove_model2.add(LSTM(GLOVE_DIM, return_sequences=True))
glove_model2.add(Flatten())
glove_model2.add(Dense(1, activation='sigmoid'))
glove_model2.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 5260, 300)         14934300  
_________________________________________________________________
flatten_2 (Flatten)          (None, 1578000)           0         
_________________________________________________________________
dense_23 (Dense)             (None, 1)                 1578001   
Total params: 16,512,301
Trainable params: 16,512,301
Non-trainable params: 0
_________________________________________________________________


In [164]:
glove_model2.layers[0].set_weights([emb_matrix])
glove_model2.layers[0].trainable = False

glove_model2.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [165]:
history2 = glove_model2.fit(X_train_emb2
                       , y_train_emb2
                       , epochs=5
                       , batch_size=32
                       , validation_data=(X_valid_emb2, y_valid_emb2)
                       , verbose=1)

Train on 74533 samples, validate on 8282 samples
Epoch 1/5
74533/74533 [==============================] - 304s 4ms/step - loss: 0.4588 - acc: 0.8406 - val_loss: 0.4640 - val_acc: 0.8582
Epoch 2/5
74533/74533 [==============================] - 293s 4ms/step - loss: 0.3073 - acc: 0.8952 - val_loss: 0.4720 - val_acc: 0.8654
Epoch 3/5
74533/74533 [==============================] - 286s 4ms/step - loss: 0.2581 - acc: 0.9113 - val_loss: 0.4751 - val_acc: 0.8666
Epoch 4/5
74533/74533 [==============================] - 292s 4ms/step - loss: 0.2322 - acc: 0.9201 - val_loss: 0.4734 - val_acc: 0.8723
Epoch 5/5
74533/74533 [==============================] - 279s 4ms/step - loss: 0.2104 - acc: 0.9277 - val_loss: 0.5164 - val_acc: 0.8708


In [166]:
# print(glove_model2.predict(X_train_emb[0:1]))
# print(X_train_emb[0].shape)

Third model trained on a generated dataset

In [167]:
# Generating data and labels
gen = 100000
noise = np.random.normal(0, 1, (gen, 100))
gen_samp = np.absolute((generator.predict(noise)))
prediction = glove_model.predict((gen_samp))
prediction = np.round(prediction)

In [168]:

# print(np.round(prediction[0:100]))
# print(np.sum(np.round(glove_model.predict(X_train_emb[0:100]))))
# print(np.sum(y_train[0:100]))


In [169]:
X_train_emb3, X_valid_emb3, y_train_emb3, y_valid_emb3 = train_test_split(gen_samp, prediction, test_size=0.3, random_state=37)

assert X_valid_emb3.shape[0] == y_valid_emb3.shape[0]
assert X_train_emb3.shape[0] == y_train_emb3.shape[0]

print('Shape of validation set:',X_valid_emb3.shape)

Shape of validation set: (30000, 5260)


In [170]:
glove_model3 = Sequential()
glove_model3.add(Embedding(NB_WORDS, GLOVE_DIM, input_length=MAX_LEN))
# glove_model3.add(LSTM(GLOVE_DIM, return_sequences=True))
# glove_model3.add(LSTM(GLOVE_DIM, return_sequences=True))
glove_model3.add(Flatten())
glove_model3.add(Dense(1, activation='sigmoid'))
glove_model3.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 5260, 300)         14934300  
_________________________________________________________________
flatten_3 (Flatten)          (None, 1578000)           0         
_________________________________________________________________
dense_24 (Dense)             (None, 1)                 1578001   
Total params: 16,512,301
Trainable params: 16,512,301
Non-trainable params: 0
_________________________________________________________________


In [171]:
glove_model3.layers[0].set_weights([emb_matrix])
glove_model3.layers[0].trainable = False

glove_model3.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [172]:
history3 = glove_model3.fit(X_train_emb3
                       , y_train_emb3
                       , epochs=5
                       , batch_size=32
                       , validation_data=(X_valid_emb3, y_valid_emb3)
                       , verbose=1)

Train on 70000 samples, validate on 30000 samples
Epoch 1/5
70000/70000 [==============================] - 348s 5ms/step - loss: 0.2424 - acc: 0.9930 - val_loss: 0.1119 - val_acc: 0.9971
Epoch 2/5
70000/70000 [==============================] - 315s 5ms/step - loss: 0.0714 - acc: 0.9973 - val_loss: 0.0411 - val_acc: 0.9982
Epoch 3/5
70000/70000 [==============================] - 307s 4ms/step - loss: 0.0283 - acc: 0.9980 - val_loss: 0.0193 - val_acc: 0.9983
Epoch 4/5
70000/70000 [==============================] - 318s 5ms/step - loss: 0.0145 - acc: 0.9984 - val_loss: 0.0103 - val_acc: 0.9986
Epoch 5/5
70000/70000 [==============================] - 333s 5ms/step - loss: 0.0094 - acc: 0.9985 - val_loss: 0.0072 - val_acc: 0.9987


In this area I am going to compare their results

In [173]:
# The model trained on the generated dataset over the real dataset
actual = y_valid_emb3
pred = np.round(glove_model2.predict(X_valid_emb3))
pred2 = np.round(glove_model3.predict(X_valid_emb3))

In [174]:
results(pred, actual) # trained on original over real
results(pred2, actual) # generated

Confusion Matrix :
[[  337  1727]
 [ 5420 22516]]
Accuracy Score : 0.7617666666666667
Report : 
              precision    recall  f1-score   support

         0.0       0.06      0.16      0.09      2064
         1.0       0.93      0.81      0.86     27936

   micro avg       0.76      0.76      0.76     30000
   macro avg       0.49      0.48      0.47     30000
weighted avg       0.87      0.76      0.81     30000


Confusion Matrix :
[[ 2042    22]
 [   17 27919]]
Accuracy Score : 0.9987
Report : 
              precision    recall  f1-score   support

         0.0       0.99      0.99      0.99      2064
         1.0       1.00      1.00      1.00     27936

   micro avg       1.00      1.00      1.00     30000
   macro avg       1.00      0.99      0.99     30000
weighted avg       1.00      1.00      1.00     30000




In [177]:
# The model trained on the generated dataset over the real dataset
actual = y_valid_emb2
pred = np.round(glove_model2.predict(X_valid_emb2))
pred2 = np.round(glove_model3.predict(X_valid_emb2))
pred3 = np.round(glove_model.predict(X_valid_emb2))


In [178]:
results(pred, actual) # trained on original over real
results(pred2, actual) # generated
results(pred3, actual) # original trained on the clothing

Confusion Matrix :
[[2112  596]
 [ 474 5100]]
Accuracy Score : 0.8708041535860903
Report : 
              precision    recall  f1-score   support

         0.0       0.82      0.78      0.80      2708
         1.0       0.90      0.91      0.91      5574

   micro avg       0.87      0.87      0.87      8282
   macro avg       0.86      0.85      0.85      8282
weighted avg       0.87      0.87      0.87      8282


Confusion Matrix :
[[  13 2695]
 [  21 5553]]
Accuracy Score : 0.6720598889157209
Report : 
              precision    recall  f1-score   support

         0.0       0.38      0.00      0.01      2708
         1.0       0.67      1.00      0.80      5574

   micro avg       0.67      0.67      0.67      8282
   macro avg       0.53      0.50      0.41      8282
weighted avg       0.58      0.67      0.54      8282


Confusion Matrix :
[[ 661 2047]
 [ 183 5391]]
Accuracy Score : 0.7307413668196088
Report : 
              precision    recall  f1-score   support

         0.0 